Repository C-D-Collaboration/photo_gallery, pull requests merged in 2021-04, with the labels that each got.

#1 Install testing gem suite
  .rspec
  Gemfile
  Gemfile.lock
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: Ready

#2 Photo model
  app/models/photo.rb
  db/migrate/20210424174631_create_photos.rb
  db/migrate/20210424174804_add_url_to_photos.rb
  db/schema.rb
  spec/models/photo_spec.rb
Labels: Adds Testing, Ready

#3 Welcome
  Gemfile
  Gemfile.lock
  app/controllers/welcome_controller.rb
  app/javascript/packs/application.js
  app/javascript/packs/src/application.scss
  app/views/layouts/_navbar.html.erb
  app/views/layouts/application.html.erb
  app/views/welcome/index.html.erb
  config/routes.rb
  config/webpack/environment.js
  package.json
  spec/features/welcome/index_spec.rb
  yarn.lock
Labels: Adds Testing, Ready

#4 Navbar
  app/assets/images/dani_reflection.jpg
  app/assets/stylesheets/application.css
  app/controllers/about_controller.rb
  app/javascript/packs/application.js
  app/views/about/index.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/layouts/application.html.erb
  config/routes.rb
  spec/features/navbar/navbar_spec.rb
Labels: Adds Testing, Ready

#5 Photo genres
  app/controllers/photos_controller.rb
  app/javascript/packs/src/application.scss
  app/models/photo.rb
  app/views/layouts/_navbar.html.erb
  app/views/layouts/application.html.erb
  app/views/photos/index.html.erb
  app/views/welcome/index.html.erb
  config/routes.rb
  db/seeds.rb
  spec/features/navbar/navbar_spec.rb
  spec/models/photo_spec.rb
Labels: Adds Testing, Ready, help wanted
