Repository C-D-Collaboration/photo_gallery, pull requests merged in 2021-05, with the labels that each got.

#6 Photos index
  app/javascript/packs/src/application.scss
  app/views/layouts/_navbar.html.erb
  app/views/photos/index.html.erb
  db/seeds.rb
  spec/features/photos/index.rb
Labels: Ready

#7 Photo index tests
  app/controllers/photos_controller.rb
  app/views/photos/index.html.erb
  spec/features/navbar/navbar_spec.rb
  spec/features/photos/index.rb
  spec/features/photos/index_spec.rb
Labels: Adds Testing, Ready

#8 Photo index styling
  app/assets/images/home.jpeg
  app/assets/images/landscape.jpeg
  app/assets/images/people.jpeg
  app/assets/images/space.jpeg
  app/assets/images/sunset.jpeg
  app/javascript/packs/src/application.scss
  app/views/photos/index.html.erb
  app/views/welcome/index.html.erb
Labels: Ready, enhancement

#9 Mailer
  .gitignore
  .vscode/settings.json
  Gemfile
  Gemfile.lock
  app/assets/images/giraffe.jpg
  app/controllers/contact_controller.rb
  app/javascript/packs/src/application.scss
  app/mailers/contact_mailer.rb
  app/poros/contact.rb
  app/views/contact/index.html.erb
  app/views/contact_mailer/new_contact_email.html.erb
  app/views/contact_mailer/new_contact_email.text.erb
  app/views/layouts/_navbar.html.erb
  app/views/welcome/index.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/routes.rb
  spec/features/contact/index_spec.rb
  spec/features/navbar/navbar_spec.rb
  spec/features/photos/index_spec.rb
  spec/features/welcome/index_spec.rb
  spec/mailers/contact_mailer_spec.rb
  spec/mailers/previews/contact_mailer_preview.rb
Labels: bug, help wanted

#10 Mailer
  app/controllers/contact_controller.rb
  app/mailers/contact_mailer.rb
  app/views/contact/index.html.erb
  app/views/contact_mailer/new_contact_email.html.erb
Labels: bug, invalid

#11 Sendgrid
  app/controllers/mail_controller.rb
  app/views/contact/index.html.erb
  config/routes.rb
  spec/requests/api/v1/mail/send_email_request_spec.rb
Labels: Adds Testing, bug, help wanted

#12 Mailer
  .gitignore
  .vscode/settings.json
  Gemfile
  Gemfile.lock
  app/assets/images/giraffe.jpg
  app/controllers/api/v1/mail_controller.rb
  app/controllers/contact_controller.rb
  app/javascript/packs/src/application.scss
  app/mailers/contact_mailer.rb
  app/poros/contact.rb
  app/views/contact/index.html.erb
  app/views/contact_mailer/new_contact_email.html.erb
  app/views/contact_mailer/new_contact_email.text.erb
  app/views/layouts/_navbar.html.erb
  app/views/welcome/index.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/routes.rb
  spec/features/contact/index_spec.rb
  spec/features/navbar/navbar_spec.rb
  spec/features/photos/index_spec.rb
  spec/features/welcome/index_spec.rb
  spec/mailers/contact_mailer_spec.rb
  spec/mailers/previews/contact_mailer_preview.rb
Labels: bug, help wanted
